O# database init, supports mysql too
database=mysql
spring.datasource.url=jdbc:mysql://petclinic-db.cfug6uwyejhe.eu-north-1.rds.amazonaws.com:3306/petclinic
spring.datasource.username=admin
spring.datasource.password=petclinic10241
spring.jpa.hibernate.ddl-auto=update
# SQL is written to be idempotent so this is safe
spring.sql.init.mode=always
